package com.example.project.model

data class CardItem(
    val abilities_and_effects: List<Any>,
    val ability_and_effect_keywords: List<Any>,
    val blitz_banned: Boolean,
    val blitz_legal: Boolean,
    val blitz_living_legend: Boolean,
    val blitz_suspended: Boolean,
    val card_keywords: List<Any>,
    val cc_banned: Boolean,
    val cc_legal: Boolean,
    val cc_living_legend: Boolean,
    val cc_suspended: Boolean,
    val commoner_banned: Boolean,
    val commoner_legal: Boolean,
    val commoner_suspended: Boolean,
    val cost: String,
    val defense: String,
    val functional_text: String,
    val functional_text_plain: String,
    val granted_keywords: List<Any>,
    val health: String,
    val intelligence: String,
    val interacts_with_keywords: List<Any>,
    val name: String,
    val pitch: String,
    val played_horizontally: Boolean,
    val power: String,
    val printings: List<Printing>,
    val removed_keywords: List<Any>,
    val type_text: String,
    val types: List<String>,
    val unique_id: String,
    val upf_banned: Boolean
)